version: "3"
services:
  web:
    build: .
    ports:
      - "1337:80"
      - "1338:1338"
    depends_on:
      - "database"
      - "redis"
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: love_letter
  redis:
    image: redis
    restart: always
